### ISSUE TITLE
Question about the svd inital method for lora_A lora_B

### ISSUE THREAD

**Issue by 2018211801** [Outsider565/LoRA-GA#10]
作者你好呀 congratulations！我在复现实验选则超参数的时候发现在拿全参数微调梯度的svd的U V赋值给AB 的时候，并不是取top奇异值对应的向量区间。这个是什么原因呀？ 如果取U@S的部分值赋值给B会不会比直接赋值U更好呢？
期待你的答复~

**Comment by Outsider565** [comment]
你好~在论文里面已经详述了这个问题，你可以再读一下推导部分

**Comment by Outsider565** [comment]
是的，在我们的理论下不正确，但我们的理论只是一种理想情况（只讨论第一步，且忽略了优化器），因此实际情况仍然需要做实验来决定。
