### ISSUE TITLE
论文细节问题

### ISSUE THREAD

**Issue by greycooker** [Outsider565/LoRA-GA#12]
您好！最近在尝试复现LoRA-GA这篇工作，感谢您的工作，我收获很大！有两个细节问题想向您请教一下：
1.LoRA-GA是否对learningrate与gradient_accumlation_steps较为敏感？对于这两个超参数的设置您有什么建议吗，LoRA-GA的学习率是否得比LoRA更小一些？
在GSM8k数据集上我尝试将learning_rate设置为3e-4,gradient_accumulation_steps设置为1以后loss始终震荡明显(loss在2-4之间震荡且不收敛），但使用LoRA并不会。参照论文将LoRA-GA的learning-rate设置为2e-5,gradient_accumulation_steps设置为32以后得到和论文一样的效果（LoRA-GA比LoRA收敛更快且效果更好）
其它超参数设置：lora_rank=16，LoRA-GA超参数：stable gamma=16，初始化的bsz=1 iter=4
2.论文中疑似有处公式疑似上下文不一致。
<img width="509" alt="image" src="https://github.com/user-attachments/assets/5355dfdf-e37e-4041-af19-4701904dec05">
分母是否应该等于更号gamma而不是gamma?在论文的算法1与代码中都是写的更号gamma

**Comment by Outsider565** [comment]
您好，感谢关注我们的工作！
1. LoRA-GA理论上的最优学习率大致就是Full-ft的最优学习率，因此调整LoRA-GA超参时，不应该参照普通的LoRA比Full大一个数量级的超参来调整，而应该按照Full的来调整。但如果出现loss震荡的确有点奇怪，请问您是用的哪个代码实现？可以贴一下你的代码吗？
2. 感谢提醒！这里的确有笔误，会在camera ready版本中修复

**Comment by greycooker** [comment]
感谢回复！我使用的是reproduce文件夹里里的代码，把llama.yaml里的learning_rate和real_batch_size分别改为3e-4与1以后loss出现了震荡，启动命令是python run_exp.py +init=gradient ++peft.lora_r=16 +peft=all wandb.name="stable-gradient-64" ++init.weight="stable" peft.use_rslora=True +dataset_name=gsm8k +seed=42
**gradient.yaml：**
mode: gradient
bsz: 1
iters: 4
direction: ArB2r
max_length: 1024
dtype: bf16
scale: stable
stable_gamma: 16
**default.yaml:**
mode: simple
lora_A: kaiming
lora_B: zeros
# This is the default way to initialize the model parameters.
dtype: bf16
**llama.yaml:**
name: LLM-Research/Meta-Llama-3-8B
type: CausalLM
epochs: 1
per_device_batch_size: 1
real_batch_size: 1
bf16: True
eval_epochs: 1
early_stopping_patience: 3
max_length: 1024
logging_steps: 1
learning_rate: 3e-4

**Comment by greycooker** [comment]
> 您好，感谢关注我们的工作！
> 
> 1. LoRA-GA理论上的最优学习率大致就是Full-ft的最优学习率，因此调整LoRA-GA超参时，不应该参照普通的LoRA比Full大一个数量级的超参来调整，而应该按照Full的来调整。但如果出现loss震荡的确有点奇怪，请问您是用的哪个代码实现？可以贴一下你的代码吗？
> 2. 感谢提醒！这里的确有笔误，会在camera ready版本中修复

感谢您的提示！也就是说如果我想比较LoRA-GA与LoRA的性能，LoRA-GA的最优学习率应该比LoRA要小一个数量级左右？但是论文里的实验部分好像LoRA和LoRA-GA的学习率设置为相同的，这是基于什么考虑呢？
![image](https://github.com/user-attachments/assets/86ab567e-dd42-48e0-a581-8dcc11221e3a)

**Comment by Outsider565** [comment]
> > 您好，感谢关注我们的工作！
> > 
> > 1. LoRA-GA理论上的最优学习率大致就是Full-ft的最优学习率，因此调整LoRA-GA超参时，不应该参照普通的LoRA比Full大一个数量级的超参来调整，而应该按照Full的来调整。但如果出现loss震荡的确有点奇怪，请问您是用的哪个代码实现？可以贴一下你的代码吗？
> > 2. 感谢提醒！这里的确有笔误，会在camera ready版本中修复
> 
> 感谢您的提示！也就是说如果我想比较LoRA-GA与LoRA的性能，LoRA-GA的学习率应该比LoRA要小一个数量级左右？但是论文里的实验部分好像LoRA和LoRA-GA的学习率设置为相同的，这是基于什么考虑呢？ ![image](https://private-user-images.githubusercontent.com/94276438/375609465-86ab567e-dd42-48e0-a581-8dcc11221e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTU1MDEsIm5iZiI6MTcyODYxNTIwMSwicGF0aCI6Ii85NDI3NjQzOC8zNzU2MDk0NjUtODZhYjU2N2UtZGQ0Mi00OGUwLWE1ODEtOGRjYzExMjIxZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAyNTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YmRiMTNmNTA5NDBlODc5NDMzZmI2YTQxNjVlNDMzYjgwMDEzYTQyYTVlMGU4ZTc0YWNmNGMwYzQwMDc4OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sl0-NvMLtc0HPaM3Ktgp0UvgphLhnMBBeIm69KwAZzM)

这个是因为我们当时follow的是pissa文章中的setting（他们是我们主要的baseline），我们和他们使用了相同的学习率来保证公平的对比。但后来我们看到lora learn less and forget less后也意识到lora的学习率应该是更高的，因此在后续更新的论文（camera ready version会在几周后放出）中讨论了不同学习率下的表现，以供lora和lora-ga公平对比。

**Comment by Outsider565** [comment]
> 感谢回复！我使用的是reproduce文件夹里里的代码，把llama.yaml里的learning_rate改为3e-4，real_batch_size改为1以后loss出现了震荡。 **启动命令** python run_exp.py +init=gradient ++peft.lora_r=16 +peft=all wandb.name="stable-gradient-64" ++init.weight="stable" peft.use_rslora=True +dataset_name=gsm8k +seed=42 **llama.yaml:** name: LLM-Research/Meta-Llama-3-8B type: CausalLM epochs: 1 per_device_batch_size: 1 real_batch_size: 1 bf16: True eval_epochs: 1 early_stopping_patience: 3 max_length: 1024 logging_steps: 1 learning_rate: 3e-4 **gradient.yaml：** mode: gradient bsz: 1 iters: 4 direction: ArB2r max_length: 1024 dtype: bf16 scale: stable stable_gamma: 16 **default.yaml:** mode: simple lora_A: kaiming lora_B: zeros dtype: bf16 **all.yaml** use_peft: true lora_r: null lora_relative_r: null lora_target_modules: all train_embeddings: false use_rslora: false use_loraplus: false loraplus_lr_ratio: 16 lora_alpha: 16

因为reproduce下的版本写的非常粗糙不推荐使用，不知道是否是因为数值精度问题导致的溢出，你可以验证一下，或者用现在的main版本，同时，如果这个**数值问题**还持续的话，你可以试试只开gradient approximation不开stable scale同时调大gradient estimation steps，我猜会有更好的性能。

**Comment by greycooker** [comment]
> > > 您好，感谢关注我们的工作！
> > > 
> > > 1. LoRA-GA理论上的最优学习率大致就是Full-ft的最优学习率，因此调整LoRA-GA超参时，不应该参照普通的LoRA比Full大一个数量级的超参来调整，而应该按照Full的来调整。但如果出现loss震荡的确有点奇怪，请问您是用的哪个代码实现？可以贴一下你的代码吗？
> > > 2. 感谢提醒！这里的确有笔误，会在camera ready版本中修复
> > 
> > 
> > 感谢您的提示！也就是说如果我想比较LoRA-GA与LoRA的性能，LoRA-GA的学习率应该比LoRA要小一个数量级左右？但是论文里的实验部分好像LoRA和LoRA-GA的学习率设置为相同的，这是基于什么考虑呢？ ![image](https://private-user-images.githubusercontent.com/94276438/375609465-86ab567e-dd42-48e0-a581-8dcc11221e3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTU1MDEsIm5iZiI6MTcyODYxNTIwMSwicGF0aCI6Ii85NDI3NjQzOC8zNzU2MDk0NjUtODZhYjU2N2UtZGQ0Mi00OGUwLWE1ODEtOGRjYzExMjIxZTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAyNTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1YmRiMTNmNTA5NDBlODc5NDMzZmI2YTQxNjVlNDMzYjgwMDEzYTQyYTVlMGU4ZTc0YWNmNGMwYzQwMDc4OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sl0-NvMLtc0HPaM3Ktgp0UvgphLhnMBBeIm69KwAZzM)
> 
> 这个是因为我们当时follow的是pissa文章中的setting（他们是我们主要的baseline），我们和他们使用了相同的学习率来保证公平的对比。但后来我们看到lora learn less and forget less后也意识到lora的学习率应该是更高的，因此在后续更新的论文（camera ready version会在几周后放出）中讨论了不同学习率下的表现，以供lora和lora-ga公平对比。

感谢回复，非常期待新版本的工作！

**Comment by greycooker** [comment]
> > 感谢回复！我使用的是reproduce文件夹里里的代码，把llama.yaml里的learning_rate改为3e-4，real_batch_size改为1以后loss出现了震荡。 **启动命令** python run_exp.py +init=gradient ++peft.lora_r=16 +peft=all wandb.name="stable-gradient-64" ++init.weight="stable" peft.use_rslora=True +dataset_name=gsm8k +seed=42 **llama.yaml:** name: LLM-Research/Meta-Llama-3-8B type: CausalLM epochs: 1 per_device_batch_size: 1 real_batch_size: 1 bf16: True eval_epochs: 1 early_stopping_patience: 3 max_length: 1024 logging_steps: 1 learning_rate: 3e-4 **gradient.yaml：** mode: gradient bsz: 1 iters: 4 direction: ArB2r max_length: 1024 dtype: bf16 scale: stable stable_gamma: 16 **default.yaml:** mode: simple lora_A: kaiming lora_B: zeros dtype: bf16 **all.yaml** use_peft: true lora_r: null lora_relative_r: null lora_target_modules: all train_embeddings: false use_rslora: false use_loraplus: false loraplus_lr_ratio: 16 lora_alpha: 16
> 
> 因为reproduce下的版本写的非常粗糙不推荐使用，不知道是否是因为数值精度问题导致的溢出，你可以验证一下，或者用现在的main版本，同时，如果这个**数值问题**还持续的话，你可以试试只开gradient approximation不开stable scale同时调大gradient estimation steps，我猜会有更好的性能。

好的！我会尝试一下新版的代码。论文里好像一直强调的是stable scale，所以我以为这种方法应该是最优的，最后想请教一下什么场景下推荐stable scale，什么场景下推荐将init_config.scale设置为gd？

**Comment by greycooker** [comment]
> > 感谢回复！我使用的是reproduce文件夹里里的代码，把llama.yaml里的learning_rate改为3e-4，real_batch_size改为1以后loss出现了震荡。 **启动命令** python run_exp.py +init=gradient ++peft.lora_r=16 +peft=all wandb.name="stable-gradient-64" ++init.weight="stable" peft.use_rslora=True +dataset_name=gsm8k +seed=42 **llama.yaml:** name: LLM-Research/Meta-Llama-3-8B type: CausalLM epochs: 1 per_device_batch_size: 1 real_batch_size: 1 bf16: True eval_epochs: 1 early_stopping_patience: 3 max_length: 1024 logging_steps: 1 learning_rate: 3e-4 **gradient.yaml：** mode: gradient bsz: 1 iters: 4 direction: ArB2r max_length: 1024 dtype: bf16 scale: stable stable_gamma: 16 **default.yaml:** mode: simple lora_A: kaiming lora_B: zeros dtype: bf16 **all.yaml** use_peft: true lora_r: null lora_relative_r: null lora_target_modules: all train_embeddings: false use_rslora: false use_loraplus: false loraplus_lr_ratio: 16 lora_alpha: 16
> 
> 因为reproduce下的版本写的非常粗糙不推荐使用，不知道是否是因为数值精度问题导致的溢出，你可以验证一下，或者用现在的main版本，同时，如果这个**数值问题**还持续的话，你可以试试只开gradient approximation不开stable scale同时调大gradient estimation steps，我猜会有更好的性能。

还有最后一个问题是reproduce版本的代码和新版代码的区别主要在哪呢？LoRA-GA的实现主要感觉是estimate_gradient函数和lora_ga_init两部分，这两部分我看reproduce和现在的代码好像写的是一样的。

**Comment by Outsider565** [comment]
> > > 感谢回复！我使用的是reproduce文件夹里里的代码，把llama.yaml里的learning_rate改为3e-4，real_batch_size改为1以后loss出现了震荡。 **启动命令** python run_exp.py +init=gradient ++peft.lora_r=16 +peft=all wandb.name="stable-gradient-64" ++init.weight="stable" peft.use_rslora=True +dataset_name=gsm8k +seed=42 **llama.yaml:** name: LLM-Research/Meta-Llama-3-8B type: CausalLM epochs: 1 per_device_batch_size: 1 real_batch_size: 1 bf16: True eval_epochs: 1 early_stopping_patience: 3 max_length: 1024 logging_steps: 1 learning_rate: 3e-4 **gradient.yaml：** mode: gradient bsz: 1 iters: 4 direction: ArB2r max_length: 1024 dtype: bf16 scale: stable stable_gamma: 16 **default.yaml:** mode: simple lora_A: kaiming lora_B: zeros dtype: bf16 **all.yaml** use_peft: true lora_r: null lora_relative_r: null lora_target_modules: all train_embeddings: false use_rslora: false use_loraplus: false loraplus_lr_ratio: 16 lora_alpha: 16
> > 
> > 
> > 因为reproduce下的版本写的非常粗糙不推荐使用，不知道是否是因为数值精度问题导致的溢出，你可以验证一下，或者用现在的main版本，同时，如果这个**数值问题**还持续的话，你可以试试只开gradient approximation不开stable scale同时调大gradient estimation steps，我猜会有更好的性能。
> 
> 好的！我会尝试一下新版的代码。论文里好像一直强调的是stable scale，所以我以为这种方法应该是最优的，想请教一下什么场景下推荐stable scale，什么场景下推荐将init_config.scale设置为gd或者其它值？

stable scale个人感觉是一个理论推导的值（对应于如果数值精度是无限大的场景），但往往随着模型变大/数值精度变低，开了stable scale更可能会出现数值精度的问题，我之前也遇到过不同领域（图片/音频）的人和我沟通过这个问题，但也几乎无解。我的个人建议是可以先开了之后试试，如果出现数值问题就关掉。

**Comment by greycooker** [comment]
> > > > 感谢回复！我使用的是reproduce文件夹里里的代码，把llama.yaml里的learning_rate改为3e-4，real_batch_size改为1以后loss出现了震荡。 **启动命令** python run_exp.py +init=gradient ++peft.lora_r=16 +peft=all wandb.name="stable-gradient-64" ++init.weight="stable" peft.use_rslora=True +dataset_name=gsm8k +seed=42 **llama.yaml:** name: LLM-Research/Meta-Llama-3-8B type: CausalLM epochs: 1 per_device_batch_size: 1 real_batch_size: 1 bf16: True eval_epochs: 1 early_stopping_patience: 3 max_length: 1024 logging_steps: 1 learning_rate: 3e-4 **gradient.yaml：** mode: gradient bsz: 1 iters: 4 direction: ArB2r max_length: 1024 dtype: bf16 scale: stable stable_gamma: 16 **default.yaml:** mode: simple lora_A: kaiming lora_B: zeros dtype: bf16 **all.yaml** use_peft: true lora_r: null lora_relative_r: null lora_target_modules: all train_embeddings: false use_rslora: false use_loraplus: false loraplus_lr_ratio: 16 lora_alpha: 16
> > > 
> > > 
> > > 因为reproduce下的版本写的非常粗糙不推荐使用，不知道是否是因为数值精度问题导致的溢出，你可以验证一下，或者用现在的main版本，同时，如果这个**数值问题**还持续的话，你可以试试只开gradient approximation不开stable scale同时调大gradient estimation steps，我猜会有更好的性能。
> > 
> > 
> > 好的！我会尝试一下新版的代码。论文里好像一直强调的是stable scale，所以我以为这种方法应该是最优的，想请教一下什么场景下推荐stable scale，什么场景下推荐将init_config.scale设置为gd或者其它值？
> 
> stable scale个人感觉是一个理论推导的值（对应于如果数值精度是无限大的场景），但往往随着模型变大/数值精度变低，开了stable scale更可能会出现数值精度的问题，我之前也遇到过不同领域（图片/音频）的人和我沟通过这个问题，但也几乎无解。我的个人建议是可以先开了之后试试，如果出现数值问题就关掉。 另外非常重要（但也没在我们第一版论文中出现的）是需要用多少batch来估计最开始的梯度，如果这个bsz比较小，可能在svd的时候容易出现奇异的值，导致后续的数值性质变差，所以建议把bsz提高一些。

感谢您的耐心回复！不过这个bsz指的是batch_size，而不是用多少batch来估计最开始的梯度吧，应该调大的是batch_size还是iter呢？
<img width="186" alt="image" src="https://github.com/user-attachments/assets/ded2a4c1-0fd8-46f8-8cb9-cd77114218ca">

**Comment by LeiWu7999** [comment]
歪个题，请问一下您在复现过程中可以使用wandb吗？我用学校服务器跑这个代码，wandb.init()一直超时，不知道是不是被墙了

**Comment by greycooker** [comment]
可以用wandb

**Comment by Outsider565** [comment]
> > > > > 感谢回复！我使用的是reproduce文件夹里里的代码，把llama.yaml里的learning_rate改为3e-4，real_batch_size改为1以后loss出现了震荡。 **启动命令** python run_exp.py +init=gradient ++peft.lora_r=16 +peft=all wandb.name="stable-gradient-64" ++init.weight="stable" peft.use_rslora=True +dataset_name=gsm8k +seed=42 **llama.yaml:** name: LLM-Research/Meta-Llama-3-8B type: CausalLM epochs: 1 per_device_batch_size: 1 real_batch_size: 1 bf16: True eval_epochs: 1 early_stopping_patience: 3 max_length: 1024 logging_steps: 1 learning_rate: 3e-4 **gradient.yaml：** mode: gradient bsz: 1 iters: 4 direction: ArB2r max_length: 1024 dtype: bf16 scale: stable stable_gamma: 16 **default.yaml:** mode: simple lora_A: kaiming lora_B: zeros dtype: bf16 **all.yaml** use_peft: true lora_r: null lora_relative_r: null lora_target_modules: all train_embeddings: false use_rslora: false use_loraplus: false loraplus_lr_ratio: 16 lora_alpha: 16
> > > > 
> > > > 
> > > > 因为reproduce下的版本写的非常粗糙不推荐使用，不知道是否是因为数值精度问题导致的溢出，你可以验证一下，或者用现在的main版本，同时，如果这个**数值问题**还持续的话，你可以试试只开gradient approximation不开stable scale同时调大gradient estimation steps，我猜会有更好的性能。
> > > 
> > > 
> > > 好的！我会尝试一下新版的代码。论文里好像一直强调的是stable scale，所以我以为这种方法应该是最优的，想请教一下什么场景下推荐stable scale，什么场景下推荐将init_config.scale设置为gd或者其它值？
> > 
> > 
> > stable scale个人感觉是一个理论推导的值（对应于如果数值精度是无限大的场景），但往往随着模型变大/数值精度变低，开了stable scale更可能会出现数值精度的问题，我之前也遇到过不同领域（图片/音频）的人和我沟通过这个问题，但也几乎无解。我的个人建议是可以先开了之后试试，如果出现数值问题就关掉。 另外非常重要（但也没在我们第一版论文中出现的）是需要用多少batch来估计最开始的梯度，如果这个bsz比较小，可能在svd的时候容易出现奇异的值，导致后续的数值性质变差，所以建议把bsz提高一些。
> 
> 感谢您的耐心回复！不过这个bsz指的是batch_size，而不是用多少batch来估计最开始的梯度吧，应该调大的是batch_size还是iter呢？ <img alt="image" width="186" src="https://private-user-images.githubusercontent.com/94276438/376012061-ded2a4c1-0fd8-46f8-8cb9-cd77114218ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODEzNTQsIm5iZiI6MTcyOTQ4MTA1NCwicGF0aCI6Ii85NDI3NjQzOC8zNzYwMTIwNjEtZGVkMmE0YzEtMGZkOC00NmY4LThjYjktY2Q3NzExNDIxOGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAzMjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNDlmZmZhOTRlNTc1ZjYyOTYzMjlkNjI0MmQyODZmMmQ3ZTkyZTIzMTYyNmU4NzU1NmJlNzUwN2U2ZmNkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DX8fbcAMscZsQrmBBOHgquWsGZFwWANcY-pzobyWIVY">

抱歉晚回复了，上周一直被别的事情耽搁，调这两个在数值上来说几乎等价（不过我个人怀疑bsz调大数值会更稳定一些，因为会少几步数值类型转换），但bsz调大可能会炸显存，iters调大可能会比较慢，所以可以根据你的实际硬件去调。

**Comment by Outsider565** [comment]
> 歪个题，请问一下您在复现过程中可以使用wandb吗？我用学校服务器跑这个代码，wandb.init()一直超时，不知道是不是被墙了

可以的，你注释掉或者科学上网
