### ISSUE TITLE
训练完成后的推理报错问题

### ISSUE THREAD

**Issue by qhmiao** [Outsider565/LoRA-GA#7]
例如在sst2数据集上，进行lora微调
CUDA_VISIBLE_DEVICES=4 python run_exp.py +init=default ++peft.lora_r=8  ++seed=0  +peft=all +dataset_name=sst2 wandb.name="lora_sst2"
训练结束后计算指标会在./utils.py报错：
```
def compute_metrics(p: PredictionOutput):
    predictions = p.predictions
    label_ids = p.label_ids # shape (batch_size, seq_len)
    if False:
        # Hard metric: the model must output exactly the same as the target
        # This should be the default evaluation metric for most tasks
        pred = np.argmax(predictions[0], axis=-1)
        num_correct = sum([np.array_equal(pred[i], label_ids[i]) for i in range(len(pred))])
        accuracy = num_correct / len(pred)
    else:
        # Soft metric: we limit the output space to the target space
        # i.e. the model classify the one with higher prob in positive and negative
        # **Use it in cola and mrpc, because it's too hard for vanilla lora**
        # Only suit for the binary classification with each label of 1 token
        label_ids = label_ids[:, 0] # remove the eos token
        unique_labels = np.unique(label_ids)
        flipped_labels = np.ones_like(label_ids) * unique_labels.sum() - label_ids
        predictions = predictions[0][:, 0, :] # **会在这里报错**
        label_prob = predictions[np.arange(len(predictions)), label_ids]
        flipped_label_prob = predictions[np.arange(len(predictions)), flipped_labels]
        num_correct = sum(label_prob > flipped_label_prob)
        accuracy = num_correct / len(label_prob)
    return {"accuracy": accuracy}

```
![图片](https://github.com/user-attachments/assets/e6fde5f5-d796-417c-80d7-85f4f6db69f8)
即predictions的维度似乎与这段计算指标代码的逻辑冲突。
我是NLP领域的新手，抱歉打扰，烦请解释一下这里的问题，是predictions的维度与正常的输出预期不符吗

**Comment by Outsider565** [comment]
这里是有两种metric，一种是soft一种是hard，soft必须要求输出的token是一个，如果是多个的话，要稍微改改代码，你可以参考prompt tuning的论文

**Comment by qhmiao** [comment]
> 这里是有两种metric，一种是soft一种是hard，soft必须要求输出的token是一个，如果是多个的话，要稍微改改代码，你可以参考prompt tuning的论文

感谢，您论文里报告的是soft的结果吗

**Comment by Outsider565** [comment]
你可以参考一下论文里是怎么写的，我现在也有点忘记当时的实现了，不过二者应该结果差距不大，你可以先用hard的写法试试

From: qhmiao ***@***.***>
Date: Wednesday, September 4, 2024 at 20:23
To: Outsider565/LoRA-GA ***@***.***>
Cc: Shaowen Wang ***@***.***>, Comment ***@***.***>
Subject: Re: [Outsider565/LoRA-GA] 训练完成后的推理报错问题 (Issue #7)

这里是有两种metric，一种是soft一种是hard，soft必须要求输出的token是一个，如果是多个的话，要稍微改改代码，你可以参考prompt tuning的论文

感谢，您论文里报告的是soft的结果吗

―
